// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as ReasonReact from "../../../node_modules/reason-react/src/ReasonReact.js";
import * as ReactFontawesome from "@fortawesome/react-fontawesome";
import * as FontawesomeFreeSolid from "@fortawesome/fontawesome-free-solid";

var component = ReasonReact.statelessComponent("Icon");

function make() {
  return ReasonReact.wrapJsForReason(ReactFontawesome, {
              icon: FontawesomeFreeSolid.faTrash
            }, null);
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
