// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../../../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "../../../node_modules/reason-react/src/ReasonReact.js";
import * as Icon$ReactTemplate from "./Icon.bs.js";
import * as Util$ReactTemplate from "../../Util.bs.js";

var component = ReasonReact.statelessComponent("ListItem");

function make(item, onDelete, onComplete, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = item[/* completed */2];
      return React.createElement("div", {
                  className: "item",
                  onClick: onComplete
                }, React.createElement("div", {
                      className: "text",
                      style: {
                        textDecoration: match !== 0 ? "line-through" : ""
                      }
                    }, Util$ReactTemplate.str(item[/* text */1])), React.createElement("div", {
                      className: "delete",
                      onClick: onDelete
                    }, ReasonReact.element(/* None */0, /* None */0, Icon$ReactTemplate.make(/* array */[]))), React.createElement("span", {
                      className: "date"
                    }, Util$ReactTemplate.str(item[/* created */3])));
    });
  return newrecord;
}

var ListItem = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("ItemList");

function make$1(list, onDelete, onComplete, _) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "list"
                }, Util$ReactTemplate.arr($$Array.of_list(List.map((function (item) {
                                return ReasonReact.element(/* Some */[item[/* id */0]], /* None */0, make(item, Curry._1(onDelete, item), Curry._1(onComplete, item), /* array */[]));
                              }), list))));
    });
  return newrecord;
}

var ItemList = /* module */[
  /* component */component$1,
  /* make */make$1
];

export {
  ListItem ,
  ItemList ,
  
}
/* component Not a pure module */
