// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";
import * as App$ReactTemplate from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ReactTemplate.make(/* array */[])), "index");

export {
  
}
/*  Not a pure module */
