// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE


var $$null = null;

function str(prim) {
  return prim;
}

function arr(prim) {
  return prim;
}

export {
  $$null ,
  str ,
  arr ,
  
}
/* null Not a pure module */
